### ISSUE TITLE
Be able to click anywhere on map

### ISSUE THREAD

**Issue by youn123** [imagination-station/frontend#18]
Right now users can only add to places that show up on search or as POIs (Points of Interests) on the map. Allow users to be able to click anywhere and add it to the route

**Comment by joshreno** [comment]
Added long press to click anywhere on the map and add the place to the route.
Investigating a bug where on clicking, the map shifts dramatically.

**Comment by joshreno** [comment]
Fixed map shifting based on undefined place_id.
Using lat-lng to get place_id returns 10 nearest places. Should consider cycling through the 10 to get one with an image as opposed to using default image if the first has no photo reference.

**Comment by joshreno** [comment]
Added cycling through first three images or default to 404 image.
