### ISSUE TITLE
New users created through signup can't log in

### ISSUE THREAD

**Issue by dbhavsar202** [imagination-station/frontend#25]

**Comment by dbhavsar202** [comment]
Fixed

**Comment by joshreno** [comment]
Just created an account in the signup page and can't log in.

**Comment by dbhavsar202** [comment]
Did you make sure the password was 6 characters long?

**Comment by joshreno** [comment]
Yes, I've tried making the password six characters, less than six, and more than six and all failed because "There is no user record corresponding to this identifier. The user may have been deleted."

**Comment by joshreno** [comment]
Should we include a warning if the password entered is less than 6 characters long?
