### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by youn123** [imagination-station/frontend#3]
Create a Home page (located in `/app/screens/Home.js`).

The Home page is where the user lands after authentication is successful. It should have:
 - Picture, name of city that user currently is in
 - List of paths (list of `/app/components/PathCard.js`) associated with that city

**Comment by youn123** [comment]
![Home](https://user-images.githubusercontent.com/19635090/65928602-90949180-e3cc-11e9-9cb9-b67931e99df3.jpg)

**Comment by dbhavsar202** [comment]
Explore page works
